import { createApp } from "vue";
import "./style.css";
import App from "./App.vue";
import Rotas from "../router/rotas.js";
import { createPinia } from "pinia";
const pinia = createPinia();
const app = createApp(App);
app.use(Rotas);
app.use(pinia);
app.mount("#app");
